import type { StaticPlan } from "../plans";

export const frenchContrastTennis: StaticPlan = {
  id: "french-contrast-tennis",
  name: "French Contrast Tennis",
  icon: "🎾",
  kind: "static",
  dayKeys: ["A", "B", "C", "D"],
  days: {
    // ─────────────────────────────────────────────
    // DAY A: Hip Hinge + Linear Power
    // ─────────────────────────────────────────────
    A: {
      title: "Hinge + Linear",
      items: [
        // Warmup
        {
          id: "a_w1",
          slot: "prep",
          name: "Ankle circles + calf raises",
          dose: "2 min",
          equipment: "None",
          hpOnly: true,
        },
        {
          id: "a_w2",
          slot: "prep",
          name: "World's greatest stretch + hip airplanes",
          dose: "3 min",
          equipment: "None",
          hpOnly: true,
        },
        {
          id: "a_w3",
          slot: "prep",
          name: "Band walks + glute activation",
          dose: "2 min",
          equipment: "Mini band",
          hpOnly: true,
        },
        {
          id: "a_w4",
          slot: "prep",
          name: "Broad jumps at 70% effort",
          dose: "3–5 reps",
          equipment: "None",
          description: "CNS primer",
          hpOnly: true,
        },

        // FC Block 1 — Hinge Power
        {
          id: "a_fc1_1",
          slot: "fc_block",
          name: "Trap bar deadlift",
          dose: "3 reps @ 80%",
          equipment: "Trap bar",
          description: "Potentiate posterior chain",
          fcBlock: 1,
          fcPosition: 1,
          restAfter: 20,
          hpOnly: true,
          suggestedLoad: "185 lb (bar + 45+25/side)",
        },
        {
          id: "a_fc1_2",
          slot: "fc_block",
          name: "Broad jump (stick landing)",
          dose: "3 reps",
          equipment: "None",
          description: "Express hip extension force",
          fcBlock: 1,
          fcPosition: 2,
          restAfter: 20,
        },
        {
          id: "a_fc1_3",
          slot: "fc_block",
          name: "KB swing (heavy)",
          dose: "5 reps",
          equipment: "KB",
          description: "Speed-strength hinge",
          fcBlock: 1,
          fcPosition: 3,
          restAfter: 20,
          suggestedLoad: "44 lb KB",
        },
        {
          id: "a_fc1_4",
          slot: "fc_block",
          name: "Banded broad jump",
          dose: "4 reps",
          equipment: "Long band",
          description: "Overspeed hip extension",
          fcBlock: 1,
          fcPosition: 4,
          restAfter: 150,
        },

        // FC Block 2 — Rotational Power
        {
          id: "a_fc2_1",
          slot: "fc_block",
          name: "Back squat (half range)",
          dose: "3 reps @ 80%",
          equipment: "Barbell",
          description: "Potentiate legs + trunk",
          fcBlock: 2,
          fcPosition: 1,
          restAfter: 20,
          hpOnly: true,
          suggestedLoad: "155 lb (bar + 45+10/side)",
        },
        {
          id: "a_fc2_2",
          slot: "fc_block",
          name: "Med-ball rotational slam",
          dose: "3/side",
          equipment: "Med ball",
          description: "High-force rotation, kinematic chain",
          fcBlock: 2,
          fcPosition: 2,
          restAfter: 20,
          suggestedLoad: "10 lb",
        },
        {
          id: "a_fc2_3",
          slot: "fc_block",
          name: "Cable step-up with rotation",
          dose: "4/side",
          equipment: "Cable + box",
          fcBlock: 2,
          fcPosition: 3,
          restAfter: 20,
          howTo:
            "Cable anchored low on the side you rotate FROM. Step up with the leg closest to the box. Rotate torso from cable side as you drive up. Mimics open-stance forehand loading pattern.",
          suggestedLoad: "20 lb cable",
        },
        {
          id: "a_fc2_4",
          slot: "fc_block",
          name: "Med-ball shotput throw (reactive)",
          dose: "4/side",
          equipment: "Med ball",
          description: "Speed rotation, unit turn",
          fcBlock: 2,
          fcPosition: 4,
          restAfter: 150,
          suggestedLoad: "10 lb",
        },

        // FC Block 3 — Linear Acceleration (ALL hpOnly)
        {
          id: "a_fc3_1",
          slot: "fc_block",
          name: "RDL (barbell)",
          dose: "3 reps @ 80%",
          equipment: "Barbell",
          description: "Potentiate hamstrings",
          fcBlock: 3,
          fcPosition: 1,
          restAfter: 20,
          hpOnly: true,
          suggestedLoad: "155 lb (bar + 45+10/side)",
        },
        {
          id: "a_fc3_2",
          slot: "fc_block",
          name: "Box jump (step down)",
          dose: "3 reps",
          equipment: "Box",
          description: "High-force vertical",
          fcBlock: 3,
          fcPosition: 2,
          restAfter: 20,
          hpOnly: true,
        },
        {
          id: "a_fc3_3",
          slot: "fc_block",
          name: "DB split squat jump",
          dose: "4/side",
          equipment: "DBs",
          description: "Speed-strength single-leg",
          fcBlock: 3,
          fcPosition: 3,
          restAfter: 20,
          hpOnly: true,
          suggestedLoad: "20 lb DBs",
        },
        {
          id: "a_fc3_4",
          slot: "fc_block",
          name: "10m sprint (or shuttle)",
          dose: "2 reps",
          equipment: "None",
          description: "Max velocity expression",
          fcBlock: 3,
          fcPosition: 4,
          restAfter: 150,
          hpOnly: true,
        },

        // Individual Exercises
        {
          id: "a_ind1",
          slot: "individual",
          name: "Single-leg RDL (DB)",
          dose: "3×6/side",
          equipment: "DBs",
          description: "Balance + posterior chain",
          suggestedLoad: "30 lb DB",
        },
        {
          id: "a_ind2",
          slot: "individual",
          name: "Half-kneeling Pallof press",
          dose: "3×8/side",
          equipment: "Cable or band",
          description: "Anti-rotation core",
          suggestedLoad: "15 lb cable",
        },

        // HP Accessory
        {
          id: "a_acc1",
          slot: "accessory",
          name: "Face pulls (band or cable)",
          dose: "3×12",
          equipment: "Band or cable",
          hpOnly: true,
          suggestedLoad: "20 lb cable",
        },
        {
          id: "a_acc2",
          slot: "accessory",
          name: "Banded lateral walks",
          dose: "3×10/side",
          equipment: "Mini band",
          hpOnly: true,
        },

        // HP Finisher — 3 rounds
        {
          id: "a_fin1",
          slot: "finisher",
          name: "Med-ball rotational slams",
          dose: "6 reps",
          equipment: "Med ball",
          restAfter: 0,
          hpOnly: true,
          finisherRounds: 3,
          suggestedLoad: "10 lb",
        },
        {
          id: "a_fin2",
          slot: "finisher",
          name: "10m shuttle run",
          dose: "1 rep",
          equipment: "None",
          restAfter: 0,
          hpOnly: true,
          finisherRounds: 3,
        },
        {
          id: "a_fin3",
          slot: "finisher",
          name: "KB swings",
          dose: "8 reps",
          equipment: "KB",
          restAfter: 30,
          hpOnly: true,
          finisherRounds: 3,
          suggestedLoad: "35 lb KB",
        },

        // Cooldown
        {
          id: "a_cd1",
          slot: "cooldown",
          name: "Walk it off + nose breathing",
          dose: "2 min",
          equipment: "None",
          hpOnly: true,
        },
      ],
    },

    // ─────────────────────────────────────────────
    // DAY B: Squat + Lateral Power
    // ─────────────────────────────────────────────
    B: {
      title: "Squat + Lateral",
      items: [
        // Warmup
        {
          id: "b_w1",
          slot: "prep",
          name: "Ankle rocks + toe raises",
          dose: "2 min",
          equipment: "None",
          hpOnly: true,
        },
        {
          id: "b_w2",
          slot: "prep",
          name: "Lunge stretch + hip 90/90 switches",
          dose: "3 min",
          equipment: "None",
          hpOnly: true,
        },
        {
          id: "b_w3",
          slot: "prep",
          name: "Mini-band lateral walks + clamshells",
          dose: "2 min",
          equipment: "Mini band",
          hpOnly: true,
        },
        {
          id: "b_w4",
          slot: "prep",
          name: "Lateral bounds at 70% effort",
          dose: "3–4 reps",
          equipment: "None",
          description: "CNS primer",
          hpOnly: true,
        },

        // FC Block 1 — Squat Power
        {
          id: "b_fc1_1",
          slot: "fc_block",
          name: "Trap bar deadlift (high handles)",
          dose: "3 reps @ 80%",
          equipment: "Trap bar",
          description: "Potentiate quads + glutes. Sub: heavy goblet squat if no trap bar.",
          fcBlock: 1,
          fcPosition: 1,
          restAfter: 20,
          hpOnly: true,
          suggestedLoad: "185 lb (bar + 45+25/side)",
        },
        {
          id: "b_fc1_2",
          slot: "fc_block",
          name: "Hurdle hops (stick each landing)",
          dose: "3 reps",
          equipment: "Hurdles or cones",
          description: "High-force vertical + landing mechanics",
          fcBlock: 1,
          fcPosition: 2,
          restAfter: 20,
        },
        {
          id: "b_fc1_3",
          slot: "fc_block",
          name: "Goblet squat jump",
          dose: "4 reps",
          equipment: "DB",
          description: "Speed-strength squat pattern",
          fcBlock: 1,
          fcPosition: 3,
          restAfter: 20,
          suggestedLoad: "25 lb DB",
        },
        {
          id: "b_fc1_4",
          slot: "fc_block",
          name: "Banded squat jumps",
          dose: "5 reps",
          equipment: "Long band",
          description: "Assisted/overspeed vertical",
          fcBlock: 1,
          fcPosition: 4,
          restAfter: 150,
        },

        // FC Block 2 — Lateral Power
        {
          id: "b_fc2_1",
          slot: "fc_block",
          name: "Front-foot elevated split squat (heavy)",
          dose: "3/side",
          equipment: "DBs + step",
          description: "Potentiate single-leg + hip stability",
          fcBlock: 2,
          fcPosition: 1,
          restAfter: 20,
          hpOnly: true,
          suggestedLoad: "35 lb DBs",
        },
        {
          id: "b_fc2_2",
          slot: "fc_block",
          name: "Lateral bound → stick (2 sec hold)",
          dose: "3/side",
          equipment: "None",
          description: "High-force lateral decel",
          fcBlock: 2,
          fcPosition: 2,
          restAfter: 20,
        },
        {
          id: "b_fc2_3",
          slot: "fc_block",
          name: "DB lateral step-up",
          dose: "4/side",
          equipment: "DB + box",
          description: "Speed-strength lateral drive, knee tracking",
          fcBlock: 2,
          fcPosition: 3,
          restAfter: 20,
          suggestedLoad: "25 lb DB",
        },
        {
          id: "b_fc2_4",
          slot: "fc_block",
          name: "Shuffle → decel (3-step stop)",
          dose: "3/direction",
          equipment: "None",
          description: "Reactive lateral speed + braking",
          fcBlock: 2,
          fcPosition: 4,
          restAfter: 150,
        },

        // FC Block 3 — Single-Leg Power (ALL hpOnly)
        {
          id: "b_fc3_1",
          slot: "fc_block",
          name: "Bulgarian split squat (heavy)",
          dose: "3/side",
          equipment: "DBs + bench",
          description: "Potentiate single-leg",
          fcBlock: 3,
          fcPosition: 1,
          restAfter: 20,
          hpOnly: true,
          kneeFlag: true,
          suggestedLoad: "30 lb DBs",
        },
        {
          id: "b_fc3_2",
          slot: "fc_block",
          name: "Single-leg box jump (step down)",
          dose: "3/side",
          equipment: "Box",
          description: "Single-leg force production",
          fcBlock: 3,
          fcPosition: 2,
          restAfter: 20,
          hpOnly: true,
          kneeFlag: true,
        },
        {
          id: "b_fc3_3",
          slot: "fc_block",
          name: "DB reverse lunge to knee drive",
          dose: "4/side",
          equipment: "DBs",
          description: "Speed-strength + hip flexion",
          fcBlock: 3,
          fcPosition: 3,
          restAfter: 20,
          hpOnly: true,
          suggestedLoad: "25 lb DBs",
        },
        {
          id: "b_fc3_4",
          slot: "fc_block",
          name: "Skater hops (continuous)",
          dose: "6 total",
          equipment: "None",
          description: "Reactive lateral elasticity",
          fcBlock: 3,
          fcPosition: 4,
          restAfter: 150,
          hpOnly: true,
        },

        // Individual Exercises
        {
          id: "b_ind1",
          slot: "individual",
          name: "Step-downs (slow eccentric, 3 sec lower)",
          dose: "3×6/side",
          equipment: "Box/step",
          description: "Knee control + decel strength",
          suggestedLoad: "BW or 15 lb DBs",
        },
        {
          id: "b_ind2",
          slot: "individual",
          name: "Copenhagen plank",
          dose: "3×20s/side",
          equipment: "Bench",
          description: "Adductor strength, groin injury prevention",
        },

        // HP Accessory
        {
          id: "b_acc1",
          slot: "accessory",
          name: "Calf raises (slow, full ROM)",
          dose: "3×12",
          equipment: "None or DBs",
          hpOnly: true,
          suggestedLoad: "30 lb DBs",
        },
        {
          id: "b_acc2",
          slot: "accessory",
          name: "Tibialis raises",
          dose: "3×15",
          equipment: "None or band",
          hpOnly: true,
        },

        // HP Finisher — 3 rounds
        {
          id: "b_fin1",
          slot: "finisher",
          name: "5-10-5 shuttle drill",
          dose: "1 rep",
          equipment: "Cones",
          restAfter: 0,
          hpOnly: true,
          finisherRounds: 3,
          howTo:
            "Set two markers 5 yards apart. Start in the middle. Sprint 5 yards right, touch. Sprint 10 yards left, touch. Sprint 5 yards back to middle.",
        },
        {
          id: "b_fin2",
          slot: "finisher",
          name: "Lateral bounds",
          dose: "8 reps",
          equipment: "None",
          restAfter: 0,
          hpOnly: true,
          finisherRounds: 3,
        },
        {
          id: "b_fin3",
          slot: "finisher",
          name: "Goblet squat jumps",
          dose: "10 reps",
          equipment: "DB",
          restAfter: 30,
          hpOnly: true,
          finisherRounds: 3,
          suggestedLoad: "25 lb DB",
        },

        // Cooldown
        {
          id: "b_cd1",
          slot: "cooldown",
          name: "Walk it off + nose breathing",
          dose: "2 min",
          equipment: "None",
          hpOnly: true,
        },
      ],
    },

    // ─────────────────────────────────────────────
    // DAY C: Upper Body + Rotation
    // ─────────────────────────────────────────────
    C: {
      title: "Upper + Rotation",
      items: [
        // Warmup
        {
          id: "c_w1",
          slot: "prep",
          name: "Scap push-ups + band pull-aparts",
          dose: "2 min",
          equipment: "Band (optional)",
          hpOnly: true,
        },
        {
          id: "c_w2",
          slot: "prep",
          name: "T-spine rotations on foam roller",
          dose: "2 min",
          equipment: "Foam roller",
          hpOnly: true,
        },
        {
          id: "c_w3",
          slot: "prep",
          name: "Bottoms-up KB hold (standing, each side 30s)",
          dose: "2 min",
          equipment: "KB",
          hpOnly: true,
        },
        {
          id: "c_w4",
          slot: "prep",
          name: "Med-ball chest passes at 70%",
          dose: "3–4 reps",
          equipment: "Med ball",
          description: "CNS primer",
          hpOnly: true,
        },

        // FC Block 1 — Pressing Power
        {
          id: "c_fc1_1",
          slot: "fc_block",
          name: "Barbell bench press",
          dose: "3 reps @ 80%",
          equipment: "Barbell + bench",
          description: "Potentiate pressing chain",
          fcBlock: 1,
          fcPosition: 1,
          restAfter: 20,
          hpOnly: true,
          suggestedLoad: "155 lb (bar + 45+10/side)",
        },
        {
          id: "c_fc1_2",
          slot: "fc_block",
          name: "Med-ball chest pass (wall)",
          dose: "4 reps",
          equipment: "Med ball",
          description: "High-force horizontal push",
          fcBlock: 1,
          fcPosition: 2,
          restAfter: 20,
          suggestedLoad: "12 lb",
        },
        {
          id: "c_fc1_3",
          slot: "fc_block",
          name: "DB push press (standing)",
          dose: "4 reps",
          equipment: "DBs",
          description: "Speed-strength, legs into press",
          fcBlock: 1,
          fcPosition: 3,
          restAfter: 20,
          suggestedLoad: "35 lb DBs",
        },
        {
          id: "c_fc1_4",
          slot: "fc_block",
          name: "Band-assisted plyo push-up",
          dose: "5 reps",
          equipment: "Long band",
          description: "Reactive pressing speed",
          fcBlock: 1,
          fcPosition: 4,
          restAfter: 150,
        },

        // FC Block 2 — Rotational Torque
        {
          id: "c_fc2_1",
          slot: "fc_block",
          name: "Landmine rotation (heavy)",
          dose: "3/side",
          equipment: "Barbell + landmine",
          description: "Potentiate trunk rotational power",
          fcBlock: 2,
          fcPosition: 1,
          restAfter: 20,
          hpOnly: true,
          howTo:
            "Barbell in landmine attachment. Hold end with both hands at chest. Drive from hips to rotate the bar from one hip to the other. Keep arms relatively straight — power comes from hips and trunk, not shoulders.",
          suggestedLoad: "70 lb (bar + 25)",
        },
        {
          id: "c_fc2_2",
          slot: "fc_block",
          name: "Med-ball rotational ground slam",
          dose: "3/side",
          equipment: "Med ball",
          description: "High-force rotation, kinematic sequencing",
          fcBlock: 2,
          fcPosition: 2,
          restAfter: 20,
          suggestedLoad: "10 lb",
        },
        {
          id: "c_fc2_3",
          slot: "fc_block",
          name: "Cable low-to-high chop (split stance)",
          dose: "4/side",
          equipment: "Cable",
          fcBlock: 2,
          fcPosition: 3,
          restAfter: 20,
          howTo:
            "Cable anchored low. Split stance with inside foot forward. Pull from low to high across body, rotating trunk. Drive from back hip.",
          suggestedLoad: "20 lb cable",
        },
        {
          id: "c_fc2_4",
          slot: "fc_block",
          name: "Band-resisted open stance rotation",
          dose: "4/side",
          equipment: "Long band",
          fcBlock: 2,
          fcPosition: 4,
          restAfter: 150,
          howTo:
            "Band anchored behind you at hip height. Stand in open stance (feet wide, slight knee bend). Rotate trunk against band resistance mimicking forehand/backhand loading. Snap back to start — feel the elastic recoil.",
        },

        // FC Block 3 — Pulling Power (ALL hpOnly)
        {
          id: "c_fc3_1",
          slot: "fc_block",
          name: "Barbell bent-over row",
          dose: "3 reps @ 80%",
          equipment: "Barbell",
          description: "Potentiate pulling chain",
          fcBlock: 3,
          fcPosition: 1,
          restAfter: 20,
          hpOnly: true,
          suggestedLoad: "135 lb (bar + 45/side)",
        },
        {
          id: "c_fc3_2",
          slot: "fc_block",
          name: "Med-ball overhead slam",
          dose: "4 reps",
          equipment: "Med ball",
          description: "High-force full-body pull-down",
          fcBlock: 3,
          fcPosition: 2,
          restAfter: 20,
          hpOnly: true,
          suggestedLoad: "12 lb",
        },
        {
          id: "c_fc3_3",
          slot: "fc_block",
          name: "1-arm cable row (explosive)",
          dose: "4/side",
          equipment: "Cable",
          description: "Speed-strength pulling, anti-rotation",
          fcBlock: 3,
          fcPosition: 3,
          restAfter: 20,
          hpOnly: true,
          suggestedLoad: "30 lb cable",
        },
        {
          id: "c_fc3_4",
          slot: "fc_block",
          name: "Band face pull (fast, snap back)",
          dose: "6 reps",
          equipment: "Long band",
          description: "Reactive shoulder external rotation",
          fcBlock: 3,
          fcPosition: 4,
          restAfter: 150,
          hpOnly: true,
        },

        // Individual Exercises
        {
          id: "c_ind1",
          slot: "individual",
          name: "Tall-kneeling cable chop (high-to-low)",
          dose: "3×8/side",
          equipment: "Cable",
          description: "Rotational core, no leg compensation",
          suggestedLoad: "20 lb cable",
        },
        {
          id: "c_ind2",
          slot: "individual",
          name: "Bottoms-up KB carry",
          dose: "3 carries/side",
          equipment: "KB",
          description: "Shoulder stability under chaos",
          suggestedLoad: "20 lb KB",
        },

        // HP Accessory
        {
          id: "c_acc1",
          slot: "accessory",
          name: "Face pulls (cable)",
          dose: "3×12",
          equipment: "Cable",
          hpOnly: true,
          suggestedLoad: "20 lb cable",
        },
        {
          id: "c_acc2",
          slot: "accessory",
          name: "Alphabet (light DBs, arms extended, draw A–Z)",
          dose: "2 rounds",
          equipment: "Light DBs",
          hpOnly: true,
        },

        // HP Finisher — 3 rounds
        {
          id: "c_fin1",
          slot: "finisher",
          name: "Med-ball rotational ground slams",
          dose: "6 reps",
          equipment: "Med ball",
          restAfter: 0,
          hpOnly: true,
          finisherRounds: 3,
          suggestedLoad: "10 lb",
        },
        {
          id: "c_fin2",
          slot: "finisher",
          name: "Med-ball overhead slams",
          dose: "8 reps",
          equipment: "Med ball",
          restAfter: 0,
          hpOnly: true,
          finisherRounds: 3,
          suggestedLoad: "12 lb",
        },
        {
          id: "c_fin3",
          slot: "finisher",
          name: "Band-resisted rotations",
          dose: "10 reps",
          equipment: "Long band",
          restAfter: 30,
          hpOnly: true,
          finisherRounds: 3,
        },

        // Cooldown
        {
          id: "c_cd1",
          slot: "cooldown",
          name: "Walk it off + nose breathing",
          dose: "2 min",
          equipment: "None",
          hpOnly: true,
        },
      ],
    },

    // ─────────────────────────────────────────────
    // DAY D: Elastic + Conditioning
    // ─────────────────────────────────────────────
    D: {
      title: "Elastic + Conditioning",
      items: [
        // Warmup
        {
          id: "d_w1",
          slot: "prep",
          name: "Jump rope (easy rhythm)",
          dose: "2 min",
          equipment: "Jump rope (optional)",
          hpOnly: true,
        },
        {
          id: "d_w2",
          slot: "prep",
          name: "Ankle pogo hops + calf bounces",
          dose: "2 min",
          equipment: "None",
          hpOnly: true,
        },
        {
          id: "d_w3",
          slot: "prep",
          name: "Hip flexor stretch + leg swings",
          dose: "2 min",
          equipment: "None",
          hpOnly: true,
        },
        {
          id: "d_w4",
          slot: "prep",
          name: "Ladder footwork (2 patterns, easy pace)",
          dose: "2 min",
          equipment: "Agility ladder (optional)",
          hpOnly: true,
        },

        // FC Block 1 — Vertical Elasticity
        {
          id: "d_fc1_1",
          slot: "fc_block",
          name: "Trap bar deadlift (lighter, 75%)",
          dose: "3 reps",
          equipment: "Trap bar",
          description: "Potentiate without grinding",
          fcBlock: 1,
          fcPosition: 1,
          restAfter: 20,
          hpOnly: true,
          suggestedLoad: "155 lb (bar + 45+10/side)",
        },
        {
          id: "d_fc1_2",
          slot: "fc_block",
          name: "Depth jump (off 18\" box, stick landing)",
          dose: "3 reps",
          equipment: "Box (18\")",
          fcBlock: 1,
          fcPosition: 2,
          restAfter: 20,
          howTo:
            "Stand on box. Step off (don't jump off). The moment your feet hit the ground, immediately jump as high as possible. Minimize ground contact time. Stick the landing on the second jump.",
        },
        {
          id: "d_fc1_3",
          slot: "fc_block",
          name: "DB squat jump",
          dose: "4 reps",
          equipment: "DBs",
          description: "Speed-strength vertical",
          fcBlock: 1,
          fcPosition: 3,
          restAfter: 20,
          suggestedLoad: "20 lb DBs",
        },
        {
          id: "d_fc1_4",
          slot: "fc_block",
          name: "Pogo hops (continuous)",
          dose: "15–20 reps",
          equipment: "None",
          description: "Max speed ground contacts",
          fcBlock: 1,
          fcPosition: 4,
          restAfter: 150,
        },

        // FC Block 2 — Lateral Elasticity
        {
          id: "d_fc2_1",
          slot: "fc_block",
          name: "Heavy DB lateral lunge",
          dose: "3/side",
          equipment: "DBs",
          description: "Potentiate adductors + lateral hip",
          fcBlock: 2,
          fcPosition: 1,
          restAfter: 20,
          hpOnly: true,
          suggestedLoad: "40 lb DBs",
        },
        {
          id: "d_fc2_2",
          slot: "fc_block",
          name: "Lateral depth jump (off 12\" box, stick)",
          dose: "3/side",
          equipment: "Box (12\")",
          fcBlock: 2,
          fcPosition: 2,
          restAfter: 20,
          howTo:
            "Stand on a low box. Step off sideways. The moment you land, immediately bound laterally away from the box. Stick the landing for 2 seconds.",
        },
        {
          id: "d_fc2_3",
          slot: "fc_block",
          name: "Banded lateral shuffle (resisted)",
          dose: "5 steps/direction",
          equipment: "Mini band",
          description: "Speed-strength lateral",
          fcBlock: 2,
          fcPosition: 3,
          restAfter: 20,
        },
        {
          id: "d_fc2_4",
          slot: "fc_block",
          name: "Skater hops (continuous, quick)",
          dose: "8 total",
          equipment: "None",
          description: "Reactive lateral elasticity",
          fcBlock: 2,
          fcPosition: 4,
          restAfter: 150,
        },

        // FC Block 3 — Multidirectional (ALL hpOnly)
        {
          id: "d_fc3_1",
          slot: "fc_block",
          name: "KB swing (heavy)",
          dose: "5 reps",
          equipment: "KB",
          description: "Potentiate hip snap",
          fcBlock: 3,
          fcPosition: 1,
          restAfter: 20,
          hpOnly: true,
          suggestedLoad: "44 lb KB",
        },
        {
          id: "d_fc3_2",
          slot: "fc_block",
          name: "Lateral bound (alternating, continuous)",
          dose: "4/side",
          equipment: "None",
          description: "High-force lateral reactive",
          fcBlock: 3,
          fcPosition: 2,
          restAfter: 20,
          hpOnly: true,
        },
        {
          id: "d_fc3_3",
          slot: "fc_block",
          name: "Single-leg 180 rotation jump",
          dose: "3/side",
          equipment: "None",
          fcBlock: 3,
          fcPosition: 3,
          restAfter: 20,
          hpOnly: true,
          howTo:
            "Stand on one leg. Jump and rotate 180 degrees in the air. Land on the same leg, stabilize for 2 seconds. Rotate back. Control > height.",
        },
        {
          id: "d_fc3_4",
          slot: "fc_block",
          name: "10m sprint to decel (3-step stop)",
          dose: "3 reps",
          equipment: "None",
          description: "Max speed + braking",
          fcBlock: 3,
          fcPosition: 4,
          restAfter: 150,
          hpOnly: true,
        },

        // Individual Exercises
        {
          id: "d_ind1",
          slot: "individual",
          name: "Line hops (front/back, 20s on/10s off)",
          dose: "3 rounds",
          equipment: "None",
          description: "Ankle stiffness + elastic contacts",
        },
        {
          id: "d_ind2",
          slot: "individual",
          name: "Lateral shuffle → split step → sprint",
          dose: "4 reps",
          equipment: "None",
          howTo:
            "Shuffle laterally 3–4 steps, hit a split step (small hop landing in athletic stance), then sprint forward 5m. Mimics reading a shot, setting up, then closing on the ball.",
        },

        // HP Accessory
        {
          id: "d_acc1",
          slot: "accessory",
          name: "Tibialis raises",
          dose: "3×15",
          equipment: "None or band",
          hpOnly: true,
        },
        {
          id: "d_acc2",
          slot: "accessory",
          name: "Single-leg calf raise (slow)",
          dose: "3×10/side",
          equipment: "None or DBs",
          hpOnly: true,
          suggestedLoad: "25 lb DB",
        },

        // HP Finisher — 4 rounds
        {
          id: "d_fin1",
          slot: "finisher",
          name: "Lateral shuffle 10m",
          dose: "1 rep",
          equipment: "None",
          restAfter: 0,
          hpOnly: true,
          finisherRounds: 4,
        },
        {
          id: "d_fin2",
          slot: "finisher",
          name: "Sprint 10m",
          dose: "1 rep",
          equipment: "None",
          restAfter: 0,
          hpOnly: true,
          finisherRounds: 4,
        },
        {
          id: "d_fin3",
          slot: "finisher",
          name: "Backpedal 10m",
          dose: "1 rep",
          equipment: "None",
          restAfter: 0,
          hpOnly: true,
          finisherRounds: 4,
        },
        {
          id: "d_fin4",
          slot: "finisher",
          name: "Med-ball ground slams",
          dose: "4 reps",
          equipment: "Med ball",
          restAfter: 30,
          hpOnly: true,
          finisherRounds: 4,
          suggestedLoad: "10 lb",
        },

        // Cooldown
        {
          id: "d_cd1",
          slot: "cooldown",
          name: "Walk it off + nose breathing",
          dose: "2 min",
          equipment: "None",
          hpOnly: true,
        },
      ],
    },
  },
};
